import type { CampaignState } from "../App";

const LEGAL =
  "Diageo te invita a disfrutar con responsabilidad. El exceso de alcohol es perjudicial para la salud. Prohibida la venta de bebidas embriagantes a menores de edad. Todas las promociones aquí descritas son válidas a nivel nacional, o hasta agotar existencias, del 18 de julio hasta el 19 de julio del 2026. Los consumidores recibirán los siguientes descuentos: 20% de descuento en Buchanan's Deluxe Whisky Escocés 12 años 750 ML (40% VOL. ALC.). Estas ofertas son válidas únicamente en compras realizadas a través de Éxito.com, Carulla.com, Éxito APP y Carulla APP. Son 1000 unidades disponibles por referencia. Válido con cualquier medio de pago. Máximo 3 unidades por transacción.";

export const DIAGEO_HOTSALE_CAMPAIGN: CampaignState = {
  campaignName: "Diageo HotSale",
  clientName: "Diageo",
  selectedFormats: ["Display"],
  includeCover: true,
  coverTemplate: "split",
  shippingDate: "19 Jul 2026",
  reviewRound: "Ronda 1",
  brandColor: "#f5c518",
  brandColors: ["#f5c518", "#1b5e2b", "#0d3d1a"],
  brandFont: null,
  selectedBg: "dark",
  logoName: null,
  logoUrl: null,
  heroName: "display-886x300.png",
  heroUrl: "/campaigns/diageo-hotsale/display-886x300.png",
  uploadedPlatforms: ["Display"],
  uploadedPieces: {},
  uploadedGroups: {},
  builderState: {
    groups: {
      "": {
        Display: [
          {
            id: "dh-1",
            name: "688×140",
            dim: "688×140",
            ar: 688 / 140,
            brand: "Diageo",
            legal: LEGAL,
            title: "20% OFF en Buchanan's Deluxe",
            imageUrl: "/campaigns/diageo-hotsale/display-688x140.png",
            fileType: "image",
            fileName: "display-688x140.png",
          },
          {
            id: "dh-2",
            name: "300×50",
            dim: "300×50",
            ar: 300 / 50,
            brand: "Diageo",
            legal: LEGAL,
            title: "20% OFF en Buchanan's Deluxe",
            imageUrl: "/campaigns/diageo-hotsale/display-300x50.png",
            fileType: "image",
            fileName: "display-300x50.png",
          },
          {
            id: "dh-3",
            name: "1280×100",
            dim: "1280×100",
            ar: 1280 / 100,
            brand: "Diageo",
            legal: LEGAL,
            title: "20% OFF en Buchanan's Deluxe",
            imageUrl: "/campaigns/diageo-hotsale/display-1280x100.png",
            fileType: "image",
            fileName: "display-1280x100.png",
          },
          {
            id: "dh-4",
            name: "737×300",
            dim: "737×300",
            ar: 737 / 300,
            brand: "Diageo",
            legal: LEGAL,
            title: "20% OFF en Buchanan's Deluxe",
            imageUrl: "/campaigns/diageo-hotsale/display-737x300.png",
            fileType: "image",
            fileName: "display-737x300.png",
          },
          {
            id: "dh-5",
            name: "886×300",
            dim: "886×300",
            ar: 886 / 300,
            brand: "Diageo",
            legal: LEGAL,
            title: "20% OFF en Buchanan's Deluxe",
            imageUrl: "/campaigns/diageo-hotsale/display-886x300.png",
            fileType: "image",
            fileName: "display-886x300.png",
          },
          {
            id: "dh-6",
            name: "344×70",
            dim: "344×70",
            ar: 344 / 70,
            brand: "Diageo",
            legal: LEGAL,
            title: "20% OFF en Buchanan's Deluxe",
            imageUrl: "/campaigns/diageo-hotsale/display-344x70.png",
            fileType: "image",
            fileName: "display-344x70.png",
          },
        ],
      },
    },
    introData: {
      "||Display": {
        title: "Display Ads",
        subtitle: "Copa Mundial FIFA 2026",
      },
    },
    piecesData: {},
    slideLegals: {
      "||Display-intro": {
        legal: LEGAL,
        brand: "Diageo",
      },
    },
    adCopyData: {},
    measuredAr: {},
  },
};
